### ISSUE TITLE
Don't work with the latest version of NodeJS

### ISSUE THREAD

**Issue by xaviplazas** [fdegier/homebridge-somfy-hotwired#17]
Don't work with the latest version of NodeJS. Homebridge requires the a newest version of NodeJS but if y intall it, this plugin don't works.

**Comment by fdegier** [comment]
Which versions are you running? For me it works fine on the latest version of Homebridge.

**Comment by xaviplazas** [comment]
> Which versions are you running? For me it works fine on the latest version of Homebridge.

I'm running Homebridge v1.7.0 (HAP v0.11.1) with node  v18.17.0. 

When homebridge starts, i get this error:

ERROR LOADING PLUGIN homebridge-somfy-hotwired:
[19/2/2024, 14:29:45] Error: The module '/usr/lib/node_modules/homebridge-somfy-hotwired/node_modules/rpio/build/Release/rpio.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at bindings (/usr/lib/node_modules/homebridge-somfy-hotwired/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-somfy-hotwired/node_modules/rpio/lib/rpio.js:17:34)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    
 
I try to uninstall, and install again the plugin but the error appears...

Can you help me?

**Comment by fdegier** [comment]
Should be fixed by https://github.com/fdegier/homebridge-somfy-hotwired/pull/19
